Yoopala.Test.Apply.WebApp/Models/Medias/MediaDetailsViewModel.cs
using Yoopala.Test.Apply.Infrastructure.Data.Models.Medias;

namespace Yoopala.Test.Apply.WebApp.Models.Medias
{
    /// <summary>
    /// View Model used to help viewing details of a media
    /// </summary>
    public class MediaDetailsViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Production { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string ReleaseDate { get; set; }

        public MediaDetailsViewModel(Media media)
        {
            ConvertFrom(media);
        }

        /// <summary>
        /// Convert a Media to MediaDetailsViewModel
        /// </summary>
        /// <param name="media">the media to convert</param>
        private void ConvertFrom(Media media)
        {
            Id = media.Id;
            Title = media.Title;
            Production = media.Production;
            Description = media.Description;
            Type = media.Type.ToString();
            ReleaseDate = media.ReleaseDate.ToShortDateString();
        }
    }
}

Yoopala.Test.Apply.WebApp/Models/Medias/MediaIndexViewModel.cs
using Yoopala.Test.Apply.WebApp.Resources;
using Yoopala.Test.Apply.Infrastructure.Data.Models.Medias;

namespace Yoopala.Test.Apply.WebApp.Models.Medias
{
    public class MediaIndexViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }

        public MediaIndexViewModel(Media media)
        {
            ConvertFrom(media);
        }

        private void ConvertFrom(Media media)
        {
            Id = media.Id;
            Title = media.Title;
            Type = media.Type.GetDisplayName();
            // TODO 8 : 
            // - Afficher le type litteral en français à l'aide d'un code déjà existant dans la solution et via "media.Type"
            // - Corriger l'affichage de celui pour "[[Music]]"

        }
    }
}

Yoopala.Test.Apply.WebApp/Models/Medias/MediaPagingIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Yoopala.Test.Apply.Common.Constants;
using Yoopala.Test.Apply.Infrastructure.Data.Models.Medias;

namespace Yoopala.Test.Apply.WebApp.Models.Medias
{
    public class MediaPagingIndexViewModel
    {
        public IEnumerable<MediaIndexViewModel> Medias { get; set; }
        public int CurrentPage { get; set; }
        public int RowsCount { get; set; }
        public int MaxPageCount { get; private set; }

        public MediaPagingIndexViewModel(List<Media> media, int currentPage, int rowsCount)
        {
            ConvertFrom(media);
            CalculatePagination(currentPage, rowsCount);
        }

        private void ConvertFrom(List<Media> media)
        {
            Medias = media.Select(m => new MediaIndexViewModel(m)).ToList();

        }

        /// <summary>
        /// Calclates nesecary values for paging
        /// </summary>
        /// <param name="currentPage">the current page</param>
        /// <param name="rowsCount">the numer of rows available</param>
        private void CalculatePagination(int currentPage, int rowsCount)
        {
            CurrentPage = currentPage;
            RowsCount = rowsCount;
            var pageCount = (double)RowsCount / Constants.PagingRowsCount;
            MaxPageCount = (int)Math.Ceiling(pageCount);
        }
    }
}

Yoopala.Test.Apply.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Yoopala.Test.Apply.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private const string TitleKey = "Title";
        private const string TitleValue = "Bienvenue";
        public IActionResult Index()
        {
            // TODO 1 : Faire en sorte d'afficher le mot "Bienvenue" sur cette page d'accueil sans modifier le code de la vue associée à cette methode
            ViewData[TitleKey] = TitleValue;
            return View();
        }
    }
}

Yoopala.Test.Apply.WebApp/Controllers/MediaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Yoopala.Test.Apply.Common.Constants;
using Yoopala.Test.Apply.WebApp.Models.Medias;
using Yoopala.Test.Apply.WebApp.Services;

namespace Yoopala.Test.Apply.WebApp.Controllers
{
    public class MediaController : Controller
    {
        private const string ErrorKey = "Error";
        private readonly IMediaService _mediaService;

        public MediaController(IMediaService mediaService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(mediaService));
        }

        public IActionResult Index(int page)
        {
            // TODO 6 : Paginer par lot de 5 les résultats de cette page
            var rowsCount = _mediaService.GetRowsCount();
            var mediaDataList = _mediaService.GetForIndex(page);
            var mediasVM = new MediaPagingIndexViewModel(mediaDataList, page, rowsCount);
            return View(mediasVM);
        }

        public IActionResult CustomSearch()
        {
            var medias = _mediaService.GetForCustomSearch().Select(m => new MediaIndexViewModel(m)).ToList();
            return View(medias);
        }

        public IActionResult Details(int? key)
        {
            // TODO 5 : Réaliser la page Details à l'instar de la page Index ( MediaDetailsViewModel ) 
            // mais qui affichera cette fois TOUTES les informations des Médias et de façon graphiquement plus adapté
            MediaDetailsViewModel mediaView = null;
            if (key.HasValue)
            {
                var media = _mediaService.GetForDetails(key.Value);
                if (media != null)
                {
                    mediaView = new MediaDetailsViewModel(media);
                }
                else
                {
                    ViewData[ErrorKey] = ErrorConstants.MediaNotFound;
                }
            }
            else
            {
                ViewData[ErrorKey] = ErrorConstants.MediaIdRequired;
            }
            
            
            return View(mediaView);
        }
    }
}

Yoopala.Test.Apply.WebApp/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>

Yoopala.Test.Apply.WebApp/Views/Media/CustomSearch.cshtml
@{
    ViewData["Title"] = "Liste des médias";
}

@using Yoopala.Test.Apply.WebApp.Models.Medias;
@model List<MediaIndexViewModel>;

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Titre</th>
            <th scope="col">Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@(item.Id)</th>
                <td>@(item.Title)</td>
                <td>@(item.Type)</td>
            </tr>
        }
    </tbody>
</table>

Yoopala.Test.Apply.WebApp/Views/Media/Details.cshtml
@{ ViewData["Title"] = "Détails de média"; }

@using Yoopala.Test.Apply.WebApp.Models.Medias;
@model MediaDetailsViewModel;

@if (ViewData.ContainsKey("Error"))
{
<div class="text-center">
    <h1 class="display-4">@ViewData["Error"]</h1>
</div> 
}
else
{
<div class="text-left mb-4">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div> 
<table class="table">
    <thead>
    </thead>
    <tbody>
        <tr>
            <td class="font-weight-bold">Titre</td>
            <td>@Model.Title</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Production</td>
            <td>@Model.Production</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Description</td>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Type</td>
            <td>@Model.Type</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Date de sortie</td>
            <td>@Model.ReleaseDate</td>
        </tr>
    </tbody>
</table>}

Yoopala.Test.Apply.WebApp/Views/Media/Index.cshtml
@{ ViewData["Title"] = "Liste des médias"; }

@using Yoopala.Test.Apply.WebApp.Models.Medias;
@model MediaPagingIndexViewModel;

<table class="table">
    <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Type</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Medias)
        {
<tr>
    <td>@(item.Title)</td>
    <td>@(item.Type)</td>
    <td>
        <a asp-area=""
           asp-controller="Media"
           asp-action="Details"
           asp-route-key="@item.Id">Voir</a>
    </td>
    @*TODO 3 : Faire en sorte que ce lien redirgie vers la bonne page Details, aux normes des Tag Helper intégrés ASP.Net Core en gardant le routing existant *@
</tr>}
    </tbody>
</table>
<br />
<nav aria-label="Media navigation">
    <ul class="pagination">
        <li class="page-item @(Model.CurrentPage >1 ? "" : "disabled")">
            <a class="page-link" asp-area="" asp-controller="Media" asp-action="Index" asp-route-page="@(Model.CurrentPage - 1)" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">@Model.CurrentPage</a></li>
        <li class="page-item @(Model.CurrentPage < Model.MaxPageCount ? "" : "disabled")">
            <a class="page-link" asp-area="" asp-controller="Media" asp-action="Index" asp-route-page="@(Model.CurrentPage + 1)" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

Yoopala.Test.Apply.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Options;
@using Yoopala.Test.Apply.Common.Configuration;
@inject IOptions<Configuration> options;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Yoopala - @options.Value.ApplicationTitle</title>
    @*TODO 7 : A l'aide du fichier appsettings.json et de la variable "options" définie ligne 2 : remplacer le texte "Test de Recrutement" ci-dessus par une valeur définie dans le fichier "appsettings.json" *@

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Yoopala - @options.Value.ApplicationTitle</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Media" asp-action="Index" asp-route-page="1">Médias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Media" asp-action="CustomSearch">Mes médias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Yoopala - @options.Value.ApplicationTitle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>